# A simple workflow
name: Simple Go deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: run go program
        run: go run hello-world.go
